fix(#86): fix validator and update structure
italia/developers-italia-api pull request #100
Opened 2022-07-29 15:52 UTC by LorenzoS92

Fix #86 
Updated validator and structure to return proper errors

2022-07-29 17:49 UTC, bfabio requested changes
Great, can we also add the tests for it, with various input?

2022-07-29 18:24 UTC, LorenzoS92 commented
OMG forgotten it, of course I will do that 🙊

2022-08-01 15:12 UTC, bfabio requested changes
Can we test all the resources, so all the tests are uniform (Logs as well)?

2022-08-01 15:12 UTC, bfabio commented on main_test.go
> +			query: "POST /v1/publishers - INVALID PAYLOAD",
```suggestion
			description: "POST publishers with invalid payload",
			query: "POST /v1/publishers",
```

This is tricky and works almost by chance (we split at space and use the first two strings for the query), but I'd say we should always provide a `description` when we want add some more information to the test.

It's not ideal and we should probably validate `query` more strictly.

2022-08-01 15:12 UTC, bfabio commented on main_test.go
> +			expectedBody:        `{"title":"can't create Publisher","detail":"invalid json","status":422,"validationErrors":[{"field":"email","rule":"email","value":"error"}]}`,
This should say `invalid format` to be consistent with the other resources, I'll add a remark at https://github.com/italia/developers-italia-api/issues/12

2022-08-01 15:12 UTC, bfabio commented on main_test.go
> +			query: "POST /v1/software - wrong payload",
```suggestion
			description: "POST software with invalid payload",
			query: "POST /v1/software",
```

2022-08-01 19:47 UTC, bfabio approved these changes

2022-08-01 19:48 UTC, merged